//Login
export const LOGIN_ATTEMP = "LOGIN_ATTEMP";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

//Signup
export const SIGNUP_ATTEMP = "SIGNUP_ATTEMP";
export const SIGNUP_RESULT = "SIGNUP_RESULT";

//Display
export const FETCH_DISPLAY_DATA = "FETCH_DISPLAY_DATA";
export const FETCH_DISPLAY_DATA_SUCCESS = "FETCH_DISPLAY_DATA_SUCCESS";
export const FETCH_DISPLAY_DATA_ERROR = "FETCH_DISPLAY_DATA_ERROR"

export const ADD_DISPLAY_DATA ="ADD_DISPLAY_DATA";
export const ADD_DISPLAY_ERROR ="ADD_DISPLAY_DATA_ERROR";
export const ADD_DISPLAY_SUCCESS ="ADD_DISPLAY_SUCCESS";